### PR TITLE
Add forbid unsafe_code

### PR DESCRIPTION
**Pull request by Muqito**
Hello

I think this could be a nice addition so tools like geiger is happy.

What do you think?

geiger-happy

### CODE REVIEW

**Review by rylev — CHANGES_REQUESTED** [review]
Awesome, but can you move this to just above the `#![deny(missing_docs)]`?

**Review by rylev — APPROVED** [review]
🎉Thanks!

**Comment by reachchris** [comment]
> 
> 
> 🎉Thanks!

Happy to contribute :)

**Comment by Muqito** [comment]
> 🎉Thanks!

Happy to contribute :)

**Pull request merged**
